controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    # questo cambia l'angolo non in applicando una forza, ma in modo statico
    # joint_position_controller:  
    #   type: position_controllers/JointGroupPositionController

    # joint_effort_controller:
    #   type: effort_controllers/JointPositionController

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
   
effort_controller:
  ros__parameters:
    joints:
      - slider_to_cart


# joint_position_controller:
#   ros__parameters:
#     joints:
#       - shoulder_1_joint
#       # - shoulder_2_joint
#       # - elbow_joint
#       # - wrist_1_joint
#       # - wrist_2_joint
#       # - wrist_3_joint
#     interface_name: position
#     pid:
#       p: 0.1
#       i: 0.01
#       d: 0.1
  

joint_effort_controller:
  ros__parameters:
    joints: 
      - shoulder_1_joint
    

    
joint_state_broadcaster:
  ros__parameters:
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.00
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true  # oppure false se vuoi controllo più preciso

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      shoulder_1_joint:
        trajectory: 0.05
        goal: 0.03
      shoulder_2_joint:
        trajectory: 0.05
        goal: 0.03
      elbow_joint:
        trajectory: 0.05
        goal: 0.03
      wrist_1_joint:
        trajectory: 0.05
        goal: 0.03
      wrist_2_joint:
        trajectory: 0.05
        goal: 0.03
      wrist_3_joint:
        trajectory: 0.05
        goal: 0.03


# hardware:
#   plugin: gazebo_ros2_control/GazeboSystem
#   joints:
#     - name: shoulder_1_joint
#       command_interface: ["effort"]
#       state_interfaces: ["position", "velocity", "effort"]
