controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    
      
joint_effort_controller:
  ros__parameters:
    joints: 
      - shoulder_1_joint
    interface_name: effort

    
joint_state_broadcaster:
  ros__parameters:
    joints:
      - shoulder_1_joint
      - shoulder_2_joint


# hardware:
#   plugin: gazebo_ros2_control/GazeboSystem
#   joints:
#     - name: shoulder_1_joint
#       command_interface: ["effort"]
#       state_interfaces: ["position", "velocity", "effort"]
