# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Frequenza di aggiornamento dei controlli

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     forward_position_controller:
#       type: position_controllers/JointGroupPositionController

#     # Questo blocco deve stare dentro controller_manager!
#     forward_position_controller:
#       ros__parameters:
#         joints:
#           - shoulder_1_joint
#           - shoulder_2_joint
#           - elbow_joint
#           - wrist_1_joint
#           - wrist_2_joint
#           - wrist_3_joint      
#         command_interfaces:
#           - position
#         state_interfaces:
#           - position
#           - velocity


# modello_braccio:
# joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 20
    
# base_to_second_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: elbow_joint
#     pid: {p: 1.0, i: 1.0, d: 0.0}

controller_manager:
  ros__parameters:
    update_rate: 50  # Frequenza di aggiornamento in Hz
    elbow_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false

elbow_position_controller:
  ros__parameters:
    joints:
      - elbow_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      elbow_joint:
        p: 100.0
        i: 1.0
        d: 10.0



